project:
  type: website
  output-dir: site
  render:
    - index.qmd
    - courses/SSR/2022-2023/SSR.qmd
    - courses/WSR_PB/2022-2023/WSR_PB.qmd
    
format:
  html:
    theme: cosmo
    toc: true
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: true
    linkcolor: '#BC0031'

website:
  title: "Statistics Lectures"
  site-url: https://shklinkenberg.github.io
  repo-url: https://github.com/ShKlinkenberg/statistics-lectures
  repo-actions: [edit, issue]
  google-analytics: "UA-107432294-1"
  page-navigation: true
  search: false
  navbar:
    background: '#BC0031'
    left:
      - text: Courses
        menu:
          - sidebar:SSR
          - sidebar:WSR

    right:
      - icon: github
        href: https://github.com/ShKlinkenberg/statistics-lectures
        aria-label: Quarto GitHub

  sidebar:
    - id: SSR
      title: "Scientific & Statistical Reasoning"
      style: "docked"
      # foreground: '#BC0031'
      background: light
      collapse-level: 2
      contents:
        - courses/SSR/2022-2023/SSR.qmd
    - id: WSR
      title: "Wetenschapsfilosofie & Statistisch Redeneren"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - courses/WSR_PB/2022-2023/WSR_PB.qmd
# 
# freeze: false